<?php

namespace App\Exports;

use App\Models\Inscrit;
use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\WithHeadings;

class InscritsExport implements FromCollection, WithHeadings
{
    public function collection()
    {
        return Inscrit::with('sitesTouristiques')->get()->map(function ($inscrit) {
            return [
                'civilite' => $inscrit->civilite,
                'nom' => $inscrit->nom,
                'prenoms' => $inscrit->prenoms,
                'genre' => $inscrit->genre,
                'email' => $inscrit->email,
                'pays_residence' => $inscrit->pays_residence,
                'continent' => $this->getContinent($inscrit->pays_residence),
                'numero_tel' => $inscrit->numero_tel,
                'nationalite' => $inscrit->nationalite,
                'langue_com' => $inscrit->langue_com,
                'intervenant' => $inscrit->inscription_tant_que == 'Intervenant' ? 1 : '0',
                'participant' => $inscrit->inscription_tant_que == 'Participant' ? 1 : '0',
                'visite_banco' => $inscrit->sitesTouristiques->contains('name', 'Visite du Parc National du Banco') ? 1 : '0',
                'balade_lagunaire' => $inscrit->sitesTouristiques->contains('name', 'Balade Lagunaire') ? 1 : '0',
                'grand_bassam' => $inscrit->sitesTouristiques->contains('name', 'Grand-Bassam') ? 1 : '0',
                'yamoussoukro' => $inscrit->sitesTouristiques->contains('name', 'Yamoussoukro') ? 1 : '0',
                'domaine_bini_foret' => $inscrit->sitesTouristiques->contains('name', 'Domaine BINI Forêt') ? 1 : '0',
                'long_sejour_bouake' => $inscrit->sitesTouristiques->contains('name', 'Long Séjour - Bouaké') ? 1 : '0',
                'long_sejour_korhogo' => $inscrit->sitesTouristiques->contains('name', 'Long Séjour - Korhogo') ? 1 : '0',
                'long_sejour_man' => $inscrit->sitesTouristiques->contains('name', 'Long Séjour - Man') ? 1 : '0',
                'Inscrit' => 1,
                'Present' => $inscrit->etat == 'validé' ? 1 : '0',
            ];
        });
    }

    public function headings(): array
    {
        return [
            'Civilité',
            'Nom',
            'Prénoms',
            'Genre',
            'Adresse email',
            'Pays de résidence',
            'Continent',
            'Numéro de téléphone',
            'Nationalité',
            'Langue de communication',
            'Intervenant', 'Participant',
            'Visite du parc national du banco',
            'Balade Lagunaire', 'Grand-Bassam',
            'Yamoussoukro', 'Domaine BINI Forêt',
            'Long Séjour-Bouaké',
            'Long Séjour-Korhogo',
            'Long Séjour-Man',
            'Inscrit(e)',
            'Présent(e)'
        ];
    }

    function getContinent($country) {
        $countryToContinent = [
            "Afghanistan" => "Asie",
            "Afrique du Sud" => "Afrique",
            "Albanie" => "Europe",
            "Algerie" => "Afrique",
            "Allemagne" => "Europe",
            "Andorre" => "Europe",
            "Angola" => "Afrique",
            "Antigua-et-Barbuda" => "Amérique",
            "Arabie Saoudite" => "Asie",
            "Argentine" => "Amérique",
            "Armenie" => "Europe",
            "Australie" => "Océanie",
            "Autriche" => "Europe",
            "Azerbaidjan" => "Europe",
            "Bahamas" => "Amérique",
            "Bahrein" => "Asie",
            "Bangladesh" => "Asie",
            "Barbade" => "Amérique",
            "Belgique" => "Europe",
            "Belize" => "Amérique",
            "Benin" => "Afrique",
            "Bhoutan" => "Asie",
            "Bielorussie" => "Europe",
            "Bolivie" => "Amérique",
            "Boznie Herzegovine" => "Europe",
            "Botswana" => "Afrique",
            "Bresil" => "Amérique",
            "Brunei Darussalam" => "Asie",
            "Bulgarie" => "Europe",
            "Burkina Faso" => "Afrique",
            "Burundi" => "Afrique",
            "Cap Vert" => "Afrique",
            "Cambodge" => "Asie",
            "Cameroun" => "Afrique",
            "Canada" => "Amérique",
            "Chili" => "Amérique",
            "Chine" => "Asie",
            "Chypre" => "Europe",
            "Colombie" => "Amérique",
            "Comores" => "Afrique",
            "Congo" => "Afrique",
            "Costa Rica" => "Amérique",
            "Côte d'Ivoire" => "Afrique",
            "Croatie" => "Europe",
            "Cuba" => "Amérique",
            "Danemark" => "Europe",
            "Djibouti" => "Afrique",
            "Dominique" => "Amérique",
            "Egypte" => "Afrique",
            "El Salvador" => "Amérique",
            "Emirates Arabes Unis" => "Asie",
            "Equateur" => "Amérique",
            "Erythree" => "Afrique",
            "Espagne" => "Europe",
            "Estonie" => "Europe",
            "Etats-Unis d'Amerique" => "Amérique",
            "Ethiopie" => "Afrique",
            "Ex République Yugoslave de Macedonie" => "Europe",
            "Federation de Russie" => "Europe",
            "Fidji" => "Océanie",
            "Finlande" => "Europe",
            "France" => "Europe",
            "Gabon" => "Afrique",
            "Gambie" => "Afrique",
            "Georgie" => "Europe",
            "Ghana" => "Afrique",
            "Grece" => "Europe",
            "Grenade" => "Amérique",
            "Guatemala" => "Amérique",
            "Guinee" => "Afrique",
            "Guinee-Bissau" => "Afrique",
            "Guinee Equatoriale" => "Afrique",
            "Guyane" => "Amérique",
            "Haiti" => "Amérique",
            "Honduras" => "Amérique",
            "Hongrie" => "Europe",
            "Îles Marshall" => "Océanie",
            "Îles Salomon" => "Océanie",
            "Inde" => "Asie",
            "Indonesie" => "Asie",
            "Iran" => "Asie",
            "Irak" => "Asie",
            "Irlande" => "Europe",
            "Islande" => "Europe",
            "Israel" => "Asie",
            "Italie" => "Europe",
            "Jamaique" => "Amérique",
            "Japon" => "Asie",
            "Jordanie" => "Asie",
            "Kazakhstan" => "Asie",
            "Kenya" => "Afrique",
            "Kirghizistan" => "Asie",
            "Kiribati" => "Océanie",
            "Koweit" => "Asie",
            "Lesotho" => "Afrique",
            "Lettonie" => "Europe",
            "Liban" => "Asie",
            "Liberia" => "Afrique",
            "Lybie" => "Afrique",
            "Liechtenstein" => "Europe",
            "Lituanie" => "Europe",
            "Luxembourg" => "Europe",
            "Madagascar" => "Afrique",
            "Malaisie" => "Asie",
            "Malawi" => "Afrique",
            "Maldives" => "Asie",
            "Mali" => "Afrique",
            "Malte" => "Europe",
            "Maroc" => "Afrique",
            "Maurice" => "Afrique",
            "Mauritanie" => "Afrique",
            "Mexique" => "Amérique",
            "Micronesie" => "Océanie",
            "Monaco" => "Europe",
            "Mongolie" => "Asie",
            "Montenegro" => "Europe",
            "Mozambique" => "Afrique",
            "Myanmar(Birmanie)" => "Asie",
            "Namibie" => "Afrique",
            "Nauru" => "Océanie",
            "Nepal" => "Asie",
            "Nicaragua" => "Amérique",
            "Niger" => "Afrique",
            "Nigeria" => "Afrique",
            "Norvege" => "Europe",
            "Nouvelle Zelande" => "Océanie",
            "Oman" => "Asie",
            "Ouganda" => "Afrique",
            "Ouzbekistan" => "Asie",
            "Pakistan" => "Asie",
            "Palaos" => "Océanie",
            "Panama" => "Amérique",
            "Papouasie-Nouvelle-Guinée" => "Océanie",
            "Paraguay" => "Amérique",
            "Pays-Bas" => "Europe",
            "Perou" => "Amérique",
            "Philippines" => "Asie",
            "Pologne" => "Europe",
            "Portugal" => "Europe",
            "Qatar" => "Asie",
            "Republique Arabe Syrienne" => "Asie",
            "Republique Centrafricaine" => "Afrique",
            "Republique de Coree" => "Asie",
            "Republique de Moldavie" => "Europe",
            "Republique Democratique du Congo" => "Afrique",
            "Republique Democratique Populaire Lao" => "Asie",
            "Republique Dominicaine" => "Amérique",
            "Republique Populaire Democratique de Coree" => "Asie",
            "Republique Tcheque" => "Europe",
            "Republique-Unie de Tanzanie" => "Afrique",
            "Roumanie" => "Europe",
            "Royaume-Uni de Grande-Bretagne et d'Irlande du Nord" => "Europe",
            "Rwanda" => "Afrique",
            "Saint-Kitts-et-Névis" => "Amérique",
            "Saint Marin" => "Europe",
            "Saint-Vincent-et-les Grenadines" => "Amérique",
            "Sainte-Lucie" => "Amérique",
            "Samoa" => "Océanie",
            "Sao Tome-et-Principe" => "Afrique",
            "Senegal" => "Afrique",
            "Serbie" => "Europe",
            "Seychelles" => "Afrique",
            "Sierra Leone" => "Afrique",
            "Singapour" => "Asie",
            "Slovaquie" => "Europe",
            "Slovenie" => "Europe",
            "Somalie" => "Afrique",
            "Soudan" => "Afrique",
            "Soudan du sud" => "Afrique",
            "Sri Lanka" => "Asie",
            "Suede" => "Europe",
            "Suisse" => "Europe",
            "Surinam" => "Amérique",
            "Swaziland" => "Afrique",
            "Tadjikistan" => "Asie",
            "Tchad" => "Afrique",
            "Thailande" => "Asie",
            "Timor-Leste" => "Asie",
            "Togo" => "Afrique",
            "Tonga" => "Océanie",
            "Trinite-et-Tobago" => "Amérique",
            "Tunisie" => "Afrique",
            "Turkmenistan" => "Asie",
            "Turquie" => "Europe",
            "Tuvalu" => "Océanie",
            "Ukraine" => "Europe",
            "Uruguay" => "Amérique",
            "Vanuatu" => "Océanie",
            "Venezuela" => "Amérique",
            "Viet Nam" => "Asie",
            "Yemen" => "Asie",
            "Zambie" => "Afrique",
            "Zimbabwe" => "Afrique"
        ];

        return isset($countryToContinent[$country]) ? $countryToContinent[$country] : null;
    }

}
